version: 0.0
os: linux
files:
  - source: ./codedeploy_artifact/
    destination: /home/ubuntu/webapp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: ubuntu
